<?php

declare(strict_types=1);

namespace Database\Seeders;

use Carbon\Carbon;
use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

final class NewsTableSeeder extends Seeder
{
    /**
     * Remove Vietnamese accents from string
     */
    private function removeVietnameseAccents(string $str): string
    {
        $accents = [
            'à',
            'á',
            'ạ',
            'ả',
            'ã',
            'â',
            'ầ',
            'ấ',
            'ậ',
            'ẩ',
            'ẫ',
            'ă',
            'ằ',
            'ắ',
            'ặ',
            'ẳ',
            'ẵ',
            'è',
            'é',
            'ẹ',
            'ẻ',
            'ẽ',
            'ê',
            'ề',
            'ế',
            'ệ',
            'ể',
            'ễ',
            'ì',
            'í',
            'ị',
            'ỉ',
            'ĩ',
            'ò',
            'ó',
            'ọ',
            'ỏ',
            'õ',
            'ô',
            'ồ',
            'ố',
            'ộ',
            'ổ',
            'ỗ',
            'ơ',
            'ờ',
            'ớ',
            'ợ',
            'ở',
            'ỡ',
            'ù',
            'ú',
            'ụ',
            'ủ',
            'ũ',
            'ư',
            'ừ',
            'ứ',
            'ự',
            'ử',
            'ữ',
            'ỳ',
            'ý',
            'ỵ',
            'ỷ',
            'ỹ',
            'đ',
            'À',
            'Á',
            'Ạ',
            'Ả',
            'Ã',
            'Â',
            'Ầ',
            'Ấ',
            'Ậ',
            'Ẩ',
            'Ẫ',
            'Ă',
            'Ằ',
            'Ắ',
            'Ặ',
            'Ẳ',
            'Ẵ',
            'È',
            'É',
            'Ẹ',
            'Ẻ',
            'Ẽ',
            'Ê',
            'Ề',
            'Ế',
            'Ệ',
            'Ể',
            'Ễ',
            'Ì',
            'Í',
            'Ị',
            'Ỉ',
            'Ĩ',
            'Ò',
            'Ó',
            'Ọ',
            'Ỏ',
            'Õ',
            'Ô',
            'Ồ',
            'Ố',
            'Ộ',
            'Ổ',
            'Ỗ',
            'Ơ',
            'Ờ',
            'Ớ',
            'Ợ',
            'Ở',
            'Ỡ',
            'Ù',
            'Ú',
            'Ụ',
            'Ủ',
            'Ũ',
            'Ư',
            'Ừ',
            'Ứ',
            'Ự',
            'Ử',
            'Ữ',
            'Ỳ',
            'Ý',
            'Ỵ',
            'Ỷ',
            'Ỹ',
            'Đ',
        ];

        $noAccents = [
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'a',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'e',
            'i',
            'i',
            'i',
            'i',
            'i',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'o',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'u',
            'y',
            'y',
            'y',
            'y',
            'y',
            'd',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'A',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'E',
            'I',
            'I',
            'I',
            'I',
            'I',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'O',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'U',
            'Y',
            'Y',
            'Y',
            'Y',
            'Y',
            'D',
        ];

        return str_replace($accents, $noAccents, $str);
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('news')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS = 1');

        $faker = Faker::create('vi_VN');

        $userIds = DB::table('users')->pluck('id')->toArray();
        $adminPartnerIds = DB::table('users')
            ->whereIn('role', ['admin', 'partner'])
            ->pluck('id')
            ->toArray();

        if (empty($userIds)) {
            $this->command->warn('No users found. Please run UsersTableSeeder first.');
            return;
        }

        if (empty($adminPartnerIds)) {
            $adminPartnerIds = [1];
        }

        $titles = [
            'Hướng dẫn đặt phòng trực tuyến nhanh chóng và tiện lợi',
            'Top 10 địa điểm du lịch gần các tòa nhà của chúng tôi',
            'Chính sách hủy phòng và hoàn tiền mới nhất',
            'Khuyến mãi đặc biệt tháng này - Giảm 30% cho khách đặt sớm',
            'Tiện ích và dịch vụ mới được bổ sung tại các tòa nhà',
            'Cảm nhận của khách hàng về dịch vụ của chúng tôi',
            'Hướng dẫn sử dụng các tiện ích trong phòng',
            'Lịch sự kiện và hoạt động trong tháng',
            'Chính sách bảo mật thông tin khách hàng',
            'Cách tiết kiệm chi phí khi lưu trú dài hạn',
            'Những điều cần biết khi check-in và check-out',
            'Dịch vụ đưa đón sân bay - Đặt trước để tiết kiệm',
            'Hướng dẫn sử dụng hệ thống đặt phòng online',
            'Chương trình khách hàng thân thiết - Tích điểm đổi quà',
            'Cập nhật giá mới cho các gói phòng',
            'Hệ thống thanh toán an toàn và tiện lợi',
            'Dịch vụ dọn phòng và giặt ủi chuyên nghiệp',
            'Hướng dẫn sử dụng WiFi và các tiện ích công nghệ',
            'Chính sách đối với khách có trẻ em',
            'Dịch vụ hỗ trợ 24/7 - Luôn sẵn sàng phục vụ',
        ];

        $summaries = [
            'Hướng dẫn chi tiết về cách đặt phòng trực tuyến một cách nhanh chóng và tiện lợi nhất, giúp bạn tiết kiệm thời gian và công sức.',
            'Khám phá top 10 địa điểm du lịch hấp dẫn gần các tòa nhà của chúng tôi, từ các điểm tham quan nổi tiếng đến những nơi ẩn mình đầy thú vị.',
            'Cập nhật chính sách hủy phòng và hoàn tiền mới nhất, đảm bảo quyền lợi tối đa cho khách hàng trong mọi tình huống.',
            'Chương trình khuyến mãi đặc biệt tháng này với mức giảm giá lên đến 30% dành cho những khách hàng đặt phòng sớm.',
            'Giới thiệu các tiện ích và dịch vụ mới được bổ sung tại các tòa nhà, nâng cao trải nghiệm của khách hàng.',
            'Lắng nghe những cảm nhận chân thực của khách hàng về dịch vụ của chúng tôi, từ những trải nghiệm thực tế nhất.',
            'Hướng dẫn chi tiết cách sử dụng các tiện ích trong phòng một cách hiệu quả và an toàn nhất.',
            'Lịch sự kiện và hoạt động đặc biệt trong tháng, mang đến những trải nghiệm thú vị cho khách hàng.',
            'Cam kết về chính sách bảo mật thông tin khách hàng, đảm bảo an toàn tuyệt đối cho dữ liệu cá nhân.',
            'Bí quyết tiết kiệm chi phí khi lưu trú dài hạn, giúp bạn tối ưu hóa ngân sách một cách thông minh.',
            'Những điều quan trọng cần biết khi check-in và check-out, giúp quá trình lưu trú diễn ra suôn sẻ.',
            'Dịch vụ đưa đón sân bay tiện lợi, đặt trước để được hưởng mức giá ưu đãi và dịch vụ tốt nhất.',
            'Hướng dẫn sử dụng hệ thống đặt phòng online từng bước, dễ hiểu và dễ thực hiện cho mọi người.',
            'Chương trình khách hàng thân thiết với hệ thống tích điểm đổi quà hấp dẫn, mang lại nhiều lợi ích.',
            'Cập nhật bảng giá mới cho các gói phòng, với nhiều lựa chọn phù hợp với mọi nhu cầu và ngân sách.',
            'Hệ thống thanh toán an toàn và tiện lợi, hỗ trợ nhiều phương thức thanh toán hiện đại.',
            'Dịch vụ dọn phòng và giặt ủi chuyên nghiệp, đảm bảo không gian sống luôn sạch sẽ và thoải mái.',
            'Hướng dẫn sử dụng WiFi và các tiện ích công nghệ trong phòng, tối ưu hóa trải nghiệm sống.',
            'Chính sách đặc biệt dành cho khách có trẻ em, tạo môi trường an toàn và thân thiện cho gia đình.',
            'Dịch vụ hỗ trợ 24/7 luôn sẵn sàng phục vụ, đảm bảo mọi nhu cầu của khách hàng được đáp ứng kịp thời.',
        ];

        $contentTemplates = [
            'Trong bài viết này, chúng tôi sẽ hướng dẫn bạn cách đặt phòng trực tuyến một cách nhanh chóng và tiện lợi nhất. Hệ thống đặt phòng của chúng tôi được thiết kế đơn giản, dễ sử dụng, phù hợp với mọi đối tượng khách hàng. Bạn chỉ cần vài bước đơn giản là có thể hoàn tất việc đặt phòng. Hãy cùng khám phá những tính năng hữu ích của hệ thống này.',
            'Việt Nam là một đất nước có nhiều điểm du lịch hấp dẫn, và các tòa nhà của chúng tôi tọa lạc tại những vị trí thuận tiện gần nhiều địa điểm nổi tiếng. Trong bài viết này, chúng tôi sẽ giới thiệu top 10 địa điểm du lịch gần các tòa nhà của chúng tôi, từ các di tích lịch sử đến các khu vui chơi giải trí hiện đại. Mỗi địa điểm đều có những nét đặc trưng riêng, hứa hẹn mang đến cho bạn những trải nghiệm khó quên.',
            'Chính sách hủy phòng và hoàn tiền là một trong những vấn đề được khách hàng quan tâm nhất. Chúng tôi luôn cập nhật và cải thiện chính sách này để đảm bảo quyền lợi tối đa cho khách hàng. Trong bài viết này, chúng tôi sẽ giải thích chi tiết về các điều khoản hủy phòng, thời gian hoàn tiền, và các trường hợp đặc biệt. Chúng tôi cam kết minh bạch và công bằng trong mọi giao dịch.',
            'Chương trình khuyến mãi đặc biệt tháng này mang đến cơ hội tiết kiệm lớn cho khách hàng. Với mức giảm giá lên đến 30%, đây là thời điểm lý tưởng để đặt phòng cho chuyến du lịch sắp tới. Chương trình áp dụng cho tất cả các loại phòng và gói dịch vụ. Hãy nhanh tay đặt phòng để không bỏ lỡ cơ hội này. Chúng tôi cũng có nhiều ưu đãi khác dành cho khách hàng thân thiết.',
            'Chúng tôi không ngừng cải thiện và bổ sung các tiện ích, dịch vụ mới để nâng cao trải nghiệm của khách hàng. Trong tháng này, chúng tôi đã bổ sung nhiều tiện ích mới như phòng gym hiện đại, bể bơi ngoài trời, và khu vui chơi trẻ em. Tất cả các tiện ích này đều được thiết kế với tiêu chuẩn cao, đảm bảo an toàn và tiện nghi cho khách hàng.',
            'Khách hàng là trung tâm của mọi hoạt động của chúng tôi. Chúng tôi luôn lắng nghe và tiếp thu những phản hồi từ khách hàng để không ngừng cải thiện dịch vụ. Trong bài viết này, chúng tôi chia sẻ những cảm nhận chân thực từ khách hàng đã sử dụng dịch vụ của chúng tôi. Những phản hồi tích cực là động lực để chúng tôi tiếp tục phấn đấu, còn những góp ý sẽ giúp chúng tôi hoàn thiện hơn.',
            'Mỗi phòng đều được trang bị đầy đủ các tiện ích hiện đại để phục vụ nhu cầu của khách hàng. Trong bài viết này, chúng tôi sẽ hướng dẫn chi tiết cách sử dụng các tiện ích trong phòng một cách hiệu quả và an toàn. Từ hệ thống điều hòa, WiFi, đến các thiết bị điện tử, mỗi tiện ích đều có những lưu ý quan trọng mà bạn nên biết để tận dụng tối đa.',
            'Tháng này, chúng tôi tổ chức nhiều sự kiện và hoạt động đặc biệt dành cho khách hàng. Từ các buổi workshop, hội thảo, đến các hoạt động giải trí, văn hóa, mỗi sự kiện đều mang đến những trải nghiệm thú vị và bổ ích. Lịch sự kiện được cập nhật thường xuyên trên website và fanpage của chúng tôi. Hãy theo dõi để không bỏ lỡ bất kỳ sự kiện nào.',
            'Bảo mật thông tin khách hàng là ưu tiên hàng đầu của chúng tôi. Chúng tôi sử dụng các công nghệ mã hóa tiên tiến để bảo vệ dữ liệu cá nhân của khách hàng. Chính sách bảo mật của chúng tôi tuân thủ các tiêu chuẩn quốc tế về bảo vệ dữ liệu. Chúng tôi cam kết không chia sẻ thông tin khách hàng cho bên thứ ba mà không có sự đồng ý.',
            'Lưu trú dài hạn có thể mang lại nhiều lợi ích về mặt tài chính nếu bạn biết cách tối ưu hóa. Trong bài viết này, chúng tôi chia sẻ những bí quyết tiết kiệm chi phí khi lưu trú dài hạn, từ việc chọn gói phù hợp đến tận dụng các ưu đãi đặc biệt. Với những mẹo này, bạn có thể tiết kiệm đáng kể chi phí mà vẫn được hưởng dịch vụ chất lượng cao.',
        ];

        foreach (range(1, 30) as $i) {
            $title = $faker->randomElement($titles);
            $slug = Str::slug($this->removeVietnameseAccents($title)) . '-' . $i;
            $userId = $faker->randomElement($userIds);
            $authorId = $faker->randomElement($adminPartnerIds);
            $status = $faker->randomElement([0, 1]);
            $publishedAt = $status === 1 ? Carbon::now()->subDays(rand(1, 30)) : null;

            DB::table('news')->insert([
                'user_id' => $userId,
                'title' => $title,
                'slug' => $slug,
                'summary' => $faker->randomElement($summaries),
                'content' => $faker->randomElement($contentTemplates),
                'status' => $status,
                'published_at' => $publishedAt,
                'image_url' => null,
                'id_image_cloudinary' => null,
                'created_by' => $authorId,
                'updated_by' => $faker->randomElement($adminPartnerIds),
                'created_at' => Carbon::now()->subDays(rand(1, 40)),
                'updated_at' => Carbon::now()->subDays(rand(1, 40)),
            ]);
        }
    }
}
