name: Laravel CI Checks

# This script will run automatically when you push code or create a Pull Request to the dev, main, or master branches
on:
  push:
    branches: [ "main", "master", "dev" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest # Runs on GitHub's Linux virtual runner

    steps:
    - name: Clone source code
      uses: actions/checkout@v3

    - name: Setup PHP 8.3
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' 
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring
        coverage: none

    - name: Copy .env file
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Install dependencies (Composer Install)
      run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Set permissions for storage and cache
      run: chmod -R 777 storage bootstrap/cache

    - name: Generate Application Key
      run: php artisan key:generate

    - name: STEP 1 - Run Code Format Check (PHP CS)
      run: composer run phpcs

    - name: STEP 2 - Run Static Analysis (Larastan / PHPStan)
      run: composer run phpstan

    - name: STEP 3 - Run Unit Tests (PHPUnit)
      run: |
        touch database/database.sqlite
        php artisan test
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
